### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by alexhung** [thulasi-ram/django-feature-toggle#1]
Any possibility for supporting python 3?

**Comment by thulasi-ram** [comment]
Would like to know if you had found any other alternative? Else I will still be supporting this project.

**Comment by alexhung** [comment]
There are a few that I was evaluating (gutter, django-waffle, etc.) None of them satisfies our requirements (gutter too complex and py 2.7 only, waffle requires the use of Django User model). This repo seems to be the closest except the py 3 support. I've made a forked of the repo and made it installable under py 3 but I'm sure there are more work to make it 2.7 backward compatible.

(There are other code issue(s) too that prevents me from actually using/evaluating this lib but I didn't dive too deep into it)

**Comment by thulasi-ram** [comment]
Thanks for the feedback. I will start porting it to py3 as well.

**Comment by thulasi-ram** [comment]
Hi @alexhung ,

PR #3  will support python 3 as well as some issues with Django 2.0. Although the unit tests passed fine I will be testing this against projects currently using it. I would appreciate your feedback as well on this.

Apart from this, can you shed some light on "code issues" you have mentioned? I would like to address them as well.

**Comment by alexhung** [comment]
@thulasi-ram The PR looks good. I think the error I got in my branch is probably resolved by the change in this: https://github.com/thulasi-ram/django-feature-toggle/pull/3/files#diff-7e4d4014bbe7be719b6d9dbe185c3aaf

**Comment by thulasi-ram** [comment]
Thanks. I have to do one more round of testing following which I will update it to a new version by this weekend.
